# Save this file inside: backend/compound_interest.py

class CompoundInterestCalculator:
    """
    ENGINE ARCHITECTURE OVERVIEW:
    ----------------------------
    This production engine handles compounding growth calculations for both retail
    consumers and professional investors. It splits outputs cleanly into discrete
    methods to fit a dual-option UI layout (Interest Wealth Gained vs. Total Balance).
    
    IN-LINE THEORY REFRESHER:
    ------------------------
    Compound interest compounds geometrically over time because interest earned in 
    Period 1 generates its own interest in Period 2. 
    Formula: Total Maturity Balance = Principal * (1 + (Rate / Freq)) ^ (Freq * Years)
    Interest Only Gained = Total Maturity Balance - Original Principal
    """

    def __init__(self, principal: float, annual_rate: float, time_years: float, compound_frequency: int = 1):
        """
        INITIALIZATION & DATA VALIDATION PIPELINE
        -----------------------------------------
        Captures state variables, converts human percentages into clean floats, 
        and acts as a gatekeeper to prevent faulty user data from crashing an APK.
        
        :param principal: Initial sum invested/borrowed (P). Must be non-negative.
        :param annual_rate: Nominal yearly interest rate as percentage (R) (e.g., 6.5 for 6.5%).
        :param time_years: Length of asset lifecycle in years (T). Must be above zero.
        :param compound_frequency: Times interest compounds per annum (N). (e.g., 12=Monthly).
        """
        # STEP 1: TYPE SANITIZATION
        # Forces string inputs from UI mobile text boxes into floating-point numbers.
        try:
            self.principal = float(principal)
            self.rate_decimal = float(annual_rate) / 100.0
            self.time_years = float(time_years)
            self.compound_frequency = int(compound_frequency)
        except (ValueError, TypeError):
            raise ValueError("Data Input Error: System requires clean numbers for execution.")

        # STEP 2: BUSINESS LOGIC ERROR CAUTIONS
        # Guard rails to capture financial anomalies before math processing.
        if self.principal < 0:
            raise ValueError("Risk Alert: Principal base cannot fall below zero.")
            
        if self.rate_decimal < 0:
            raise ValueError("Risk Alert: Interest rate metric cannot be negative.")
            
        if self.time_years <= 0:
            raise ValueError("Timeline Error: Investment duration must be greater than zero years.")
            
        if self.compound_frequency <= 0:
            raise ValueError("Frequency Error: Annual compounding cycles must be 1 or higher.")

    def get_total_amount(self) -> float:
        """
        OUTPUT OPTION A: TOTAL MATURITY WEALTH
        -------------------------------------
        Executes exponential compounding. 
        Math breakdown:
        1. Calculate periodic rate -> (Annual Rate / Compounds Per Year)
        2. Calculate total compounding periods -> (Compounds Per Year * Total Years)
        3. Raise periodic factor to total periods power, then multiply by principal.
        """
        periodic_rate = self.rate_decimal / self.compound_frequency
        total_periods = self.compound_frequency * self.time_years
        
        # Exponential Growth Equation: A = P * (1 + r/n)^(n*t)
        total_maturity_balance = self.principal * ((1.0 + periodic_rate) ** total_periods)
        
        # Bankers' rounding to 2 decimal places for precise currency display
        return round(total_maturity_balance, 2)

    def get_interest_only(self) -> float:
        """
        OUTPUT OPTION B: PURE INTEREST EARNED
        -------------------------------------
        Isolates the wealth generated by stripping away the starting principal.
        Formula: Interest = Accumulated Balance - Initial Capital
        """
        total_balance = self.get_total_amount()
        pure_interest_gained = total_balance - self.principal
        
        return round(pure_interest_gained, 2)
