# Save this file inside: backend/sip_investment.py

class SipInvestmentCalculator:
    """
    ENGINE ARCHITECTURE OVERVIEW:
    ----------------------------
    This engine computes wealth generation from recurring monthly asset contributions.
    It serves everyday consumers tracking mutual funds and professionals modeling savings goals.
    Outputs are isolated into separate class methods to fit a multi-option UI layout.
    
    IN-LINE THEORY REFRESHER:
    ------------------------
    An SIP utilizes annuity mathematics. Because deposits are made sequentially every 
    month, earlier payments compound for a longer duration than later ones.
    Formula: Maturity Balance = P * [((1 + i)^n - 1) / i] * (1 + i)
    Total Invested = Monthly Capital * Total Months
    Wealth Gained = Maturity Balance - Total Invested
    """

    def __init__(self, monthly_investment: float, expected_annual_return: float, tenure_years: float):
        """
        INITIALIZATION & INPUT SANITIZATION PIPELINE
        -------------------------------------------
        Converts text input strings from mobile entry elements into clean floats.
        Applies logic gates to prevent calculation errors or mobile app background failure.
        
        :param monthly_investment: Fixed cash amount deposited every month (P). Must be greater than zero.
        :param expected_annual_return: Estimated yearly growth/yield percentage (R) (e.g., 12.0 for 12%).
        :param tenure_years: Total investment timeline measured in years (T). Must be above zero.
        """
        # STEP 1: TYPE SANITIZATION
        try:
            self.monthly_investment = float(monthly_investment)
            self.annual_return = float(expected_annual_return)
            self.tenure_years = float(tenure_years)
        except (ValueError, TypeError):
            raise ValueError("Data Input Error: Clean numerical entries are required to calculate SIP.")

        # STEP 2: BUSINESS LOGIC GUARD RAILS (Error Cautioning)
        if self.monthly_investment <= 0:
            raise ValueError("Investment Error: Monthly contribution amount must be greater than zero.")
            
        if self.annual_return < 0:
            raise ValueError("Risk Alert: Expected rate of return cannot be negative.")
            
        if self.tenure_years <= 0:
            raise ValueError("Timeline Error: Investment tenure must be greater than zero years.")

        # STEP 3: CONVERT YEARLY VARIABLES TO MONTHLY INCREMENTS
        self.monthly_rate = (self.annual_return / 100.0) / 12.0
        self.total_months = int(self.tenure_years * 12)

    def get_total_invested(self) -> float:
        """
        OUTPUT OPTION A: TOTAL PRINCIPAL INVESTED
        -----------------------------------------
        Calculates the out-of-pocket cash contributed by the user over time.
        Formula: Total Invested = Monthly Amount * Total Months
        """
        return round(self.monthly_investment * self.total_months, 2)

    def get_total_maturity_amount(self) -> float:
        """
        OUTPUT OPTION B: ESTIMATED FINAL MATURITY BALANCE
        -------------------------------------------------
        Executes the monthly annuity compounding equation.
        Handles zero-percent return scenarios as a safe backup logic constraint.
        """
        # Special logic check for 0% return investments (cash hoarding baseline)
        if self.monthly_rate == 0:
            return round(self.monthly_investment * self.total_months, 2)
            
        # Standard Industry Formula: M = P * [((1 + i)^n - 1) / i] * (1 + i)
        compounded_growth = (1.0 + self.monthly_rate) ** self.total_months
        numerator = compounded_growth - 1.0
        
        calculated_maturity = self.monthly_investment * (numerator / self.monthly_rate) * (1.0 + self.monthly_rate)
        return round(calculated_maturity, 2)

    def get_wealth_gained_only(self) -> float:
        """
        OUTPUT OPTION C: PURE MARKET WEALTH GAINED (PROFIT)
        ---------------------------------------------------
        Isolates the absolute interest/growth returns generated by the market.
        Formula: Wealth Gained = Total Maturity Value - Total Invested Principal
        """
        maturity_value = self.get_total_maturity_amount()
        invested_principal = self.get_total_invested()
        
        pure_profit = maturity_value - invested_principal
        return round(pure_profit, 2)
